// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectionStatus():Promise<main.Connection>;

export function GetDisplayServerType():Promise<main.DisplayServerType>;

export function GetHotKeys():Promise<Array<string>>;

export function GetModelName():Promise<string>;

export function GetPrompt():Promise<string>;

export function LastOcrResponse():Promise<string>;

export function LastOllamaResponse():Promise<string>;

export function OllamaConnectionStatus():Promise<string>;

export function OllamaProcessing():Promise<boolean>;

export function OrcaVersion(arg1:string):Promise<string>;

export function SetPrompt(arg1:string):Promise<void>;

export function TryCreateClient():Promise<boolean>;
