// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectionStatus():Promise<main.Connection>;

export function GetHotKeys():Promise<Array<main.HotkeyWithMetadata>>;

export function OrcaVersion(arg1:string):Promise<string>;

export function TryCreateClient():Promise<boolean>;
