// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectionStatus() {
  return window['go']['main']['App']['ConnectionStatus']();
}

export function GetDisplayServerType() {
  return window['go']['main']['App']['GetDisplayServerType']();
}

export function GetHotKeys() {
  return window['go']['main']['App']['GetHotKeys']();
}

export function GetModelName() {
  return window['go']['main']['App']['GetModelName']();
}

export function GetPrompt() {
  return window['go']['main']['App']['GetPrompt']();
}

export function LastOcrResponse() {
  return window['go']['main']['App']['LastOcrResponse']();
}

export function LastOllamaResponse() {
  return window['go']['main']['App']['LastOllamaResponse']();
}

export function OllamaConnectionStatus() {
  return window['go']['main']['App']['OllamaConnectionStatus']();
}

export function OllamaProcessing() {
  return window['go']['main']['App']['OllamaProcessing']();
}

export function OrcaVersion(arg1) {
  return window['go']['main']['App']['OrcaVersion'](arg1);
}

export function SetPrompt(arg1) {
  return window['go']['main']['App']['SetPrompt'](arg1);
}

export function TryCreateClient() {
  return window['go']['main']['App']['TryCreateClient']();
}
