// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectionStatus() {
  return window['go']['main']['App']['ConnectionStatus']();
}

export function GetDisplayServerType() {
  return window['go']['main']['App']['GetDisplayServerType']();
}

export function GetHotKeys() {
  return window['go']['main']['App']['GetHotKeys']();
}

export function OllamaConnectionStatus() {
  return window['go']['main']['App']['OllamaConnectionStatus']();
}

export function OrcaVersion(arg1) {
  return window['go']['main']['App']['OrcaVersion'](arg1);
}

export function SetPrompt(arg1) {
  return window['go']['main']['App']['SetPrompt'](arg1);
}

export function TryCreateClient() {
  return window['go']['main']['App']['TryCreateClient']();
}
