// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectedToOrca():Promise<boolean>;

export function OrcaVersion(arg1:string):Promise<string>;

export function TakeScreenshot():Promise<string>;

export function TryCreateClient():Promise<string>;
