// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectedToOrca() {
  return window['go']['main']['App']['ConnectedToOrca']();
}

export function OrcaVersion(arg1) {
  return window['go']['main']['App']['OrcaVersion'](arg1);
}

export function TakeScreenshot() {
  return window['go']['main']['App']['TakeScreenshot']();
}

export function TryCreateClient() {
  return window['go']['main']['App']['TryCreateClient']();
}
